import { Inter ,Roboto } from "next/font/google";
import "./globals.css";
import Chatbot from "@/components/chatbot";
const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({ weight: ['400','700'],
  subsets: ["latin"]
 });

export const metadata = {
  title: {
    default: "Chatbot",
    template: "%s - Umer Malik",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto. className}>{children}
      <Chatbot />
      </body>
    </html>
  );
}
